#!/bin/bash
var1=$1

#3 est le file descriptor 
exec 3<>/dev/tcp/$var1/28772
line=""

while [ "$line" != "exit" ]
do
	echo -n "> "
	read -r line
	echo "$line" >&3
	read -r reponse <&3
	echo "$reponse"
done

exec 3<&-
exec 3>&-
